- name: Set plant-diary variables
  ansible.builtin.set_fact:
    src_dir: "{{ ansible_facts['env']['HOME'] }}/src"
    backup_timestamp: "{{ now().strftime('%Y%m%d%H%M%S') }}"

- name: Check if plant-diary data directory exists on remote
  ansible.builtin.stat:
    path: "{{ src_dir }}/plant-diary/data"
  register: plant_diary_data_dir

- name: Create local backup directory for plant-diary data
  ansible.builtin.file:
    path: "{{ playbook_dir }}/backup/plant-diary/data_{{ backup_timestamp }}"
    state: directory
  delegate_to: localhost
  when: plant_diary_data_dir.stat.exists

- name: Backup plant-diary data directory from remote to local
  ansible.posix.synchronize:
    src: "{{ src_dir }}/plant-diary/data/"
    dest: "{{ playbook_dir }}/backup/plant-diary/data_{{ backup_timestamp }}/"
    mode: pull
  when: plant_diary_data_dir.stat.exists

- name: Install required packages for plant-diary
  ansible.builtin.apt:
    name:
      - imagemagick
      - fswebcam
    state: present
  become: yes

- name: Clone plant-diary
  ansible.builtin.git:
    repo: "https://github.com/canpok1/plant-diary.git"
    dest: "{{ src_dir }}/plant-diary"
    version: main
    force: yes

- name: check .env file exists
  ansible.builtin.stat:
    path: "{{ src_dir }}/plant-diary/.env"
  register: env_file

- name: Create .env file for plant-diary
  ansible.builtin.copy:
    src: "{{ src_dir }}/plant-diary/.env.example"
    dest: "{{ src_dir }}/plant-diary/.env"
    remote_src: yes
    force: no
  when: not env_file.stat.exists

- name: Replace placeholders in .env file
  ansible.builtin.replace:
    path: "{{ src_dir }}/plant-diary/.env"
    regexp: 'your_api_key_here'
    replace: "{{ gemini_api_key }}"
  when: not env_file.stat.exists

- name: Login to GHCR
  community.docker.docker_login:
    registry_url: ghcr.io
    username: "USERNAME"
    password: "{{ lookup('env', 'GH_TOKEN') }}"

- name: Run Docker Compose up for plant-diary
  community.docker.docker_compose_v2:
    project_src: "{{ src_dir }}/plant-diary"
    state: present

- name: Add execute permission to capture_auto.sh
  ansible.builtin.file:
    path: "{{ src_dir }}/plant-diary/scripts/capture_auto.sh"
    mode: '0755'

- name: Add cron job to run capture_auto.sh
  ansible.builtin.cron:
    name: "Run capture script"
    job: "{{ src_dir }}/plant-diary/scripts/capture_auto.sh --api-url http://localhost:8080 --script-key {{ script_key }}"
    minute: "0"
    hour: "3"
